name: Test

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
    runs-on: ubuntu-latest
    name: Test with Go ${{ matrix.go-version }}
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - uses: actions/checkout@v2
      - run: |
          make build cover
          bash <(curl -s https://codecov.io/bash)
